name: sentinel_env
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.7
  - cudatoolkit
  - cudnn=7.6.5
  - jupyter=1.0.0
  - nb_conda=2.2.1
  - scikit-learn=0.22.1
  - pip=19.2.3
  - pytorch=1.4.0
  - tqdm=4.36.1
  - xgboost
  - scikit-optimize
  - lightgbm
  - catboost 
